### ISSUE TITLE
Issue with unknown parameter for row X

### ISSUE THREAD

**Issue by orschiro** [anjanasilva/AJ-CSV-to-DataTable#1]
Dear @anjanasilva,

Thank you so much for this great plugin!

It almost solved an essential need to display the content of a csv hosted on Dropbox on one of your pages. However, there is still the following error that I cannot get rid of.

![image](https://cloud.githubusercontent.com/assets/170947/12676576/c34f06dc-c693-11e5-85ae-16ce3b82113d.png)

I opened the csv file with LibreOffice Calc, checked for any errors and re-saved it. 

Then I embedded the csv as follows:

```
[aj-csv2dt src=https://www.dropbox.com/s/9893tbf0iyrnwhg/courses-overview-table.csv?raw=1 id=courses_overview_table]
```

You may want to check out the live version here: 

http://scorai.org/teaching/course-descriptions/

Could you advise me what is causing the error?

Thankfully,

~Robert

**Comment by anjanasilva** [comment]
Dear @orschiro 

Thanks for your feedback. 

I cannot see your live version in the given link. By the way, did you try giving the link without "?raw=1", ie :- [aj-csv2dt src=https://www.dropbox.com/s/9893tbf0iyrnwhg/courses-overview-table.csv id=courses_overview_table] 

Or , perhaps some of the special characters such as "<" , "/" in your csv file causing this issue. I will further investigate and post and update if necessary. Meantime, please feel free to share your findings. 

Many thanks,
~Anjana

**Comment by orschiro** [comment]
Dear @anjanasilva,

I appreciate your help!

Please view the live version at http://scorai.org/test/.

On this page, I tried the following code:

```
<h1>Without raw=1</h1>
[aj-csv2dt src=https://www.dropbox.com/s/9893tbf0iyrnwhg/courses-overview-table.csv id=courses_overview_table]
```

As you can see, this code only produces garbage.

~Robert

**Comment by anjanasilva** [comment]
Dear @orschiro

Sorry, this plugin currently does not support anything but a raw CSV file. The above URL (https://www.dropbox.com/s/9893tbf0iyrnwhg/courses-overview-table.csv) does not contain a raw CSV file.

**Comment by orschiro** [comment]
OK, thanks for your reply! :-)
